//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyVMAdmin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cmd.exe")]
        public string CommandShellFileName {
            get {
                return ((string)(this["CommandShellFileName"]));
            }
            set {
                this["CommandShellFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CommandShellArgs {
            get {
                return ((string)(this["CommandShellArgs"]));
            }
            set {
                this["CommandShellArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\VMware\\Infrastructure\\Virtual Infrastructure Client\\Launch" +
            "er\\VpxClient.exe")]
        public string vSphereClientFileName {
            get {
                return ((string)(this["vSphereClientFileName"]));
            }
            set {
                this["vSphereClientFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vSphereClientArgs {
            get {
                return ((string)(this["vSphereClientArgs"]));
            }
            set {
                this["vSphereClientArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe")]
        public string powerCLIFileName {
            get {
                return ((string)(this["powerCLIFileName"]));
            }
            set {
                this["powerCLIFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-psc \"C:\\Program Files (x86)\\VMware\\Infrastructure\\vSphere PowerCLI\\vim.psc1\" -no" +
            "e -c \". \\\"C:\\Program Files (x86)\\VMware\\Infrastructure\\vSphere PowerCLI\\Scripts\\" +
            "Initialize-PowerCLIEnvironment.ps1\\\"\"")]
        public string powerCLIArgs {
            get {
                return ((string)(this["powerCLIArgs"]));
            }
            set {
                this["powerCLIArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username")]
        public string DefaultUsername {
            get {
                return ((string)(this["DefaultUsername"]));
            }
            set {
                this["DefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("domainname")]
        public string DefaultDomain {
            get {
                return ((string)(this["DefaultDomain"]));
            }
            set {
                this["DefaultDomain"] = value;
            }
        }
    }
}
